export enum IpcChannel {
  GET_SETTINGS = "GET_SETTINGS",
  GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS",
  SET_SETTINGS = "SET_SETTINGS",
  SET_SETTINGS_SUCCESS = "SET_SETTINGS_SUCCESS",
  PLAY_START_GONG = "PLAY_START_GONG",
  PLAY_END_GONG = "PLAY_END_GONG",
  GET_BREAK_END_TIME = "GET_BREAK_END_TIME",
  GET_BREAK_END_TIME_SUCCESS = "GET_BREAK_END_TIME_SUCCESS",
  SHOW_BREAK_WINDOW = "SHOW_BREAK_WINDOW",
  ERROR = "ERROR"
}
