export enum IpcChannel {
  ERROR = "ERROR",
  GET_BREAK_END_TIME = "GET_BREAK_END_TIME",
  GET_SETTINGS = "GET_SETTINGS",
  PLAY_END_GONG = "PLAY_END_GONG",
  PLAY_START_GONG = "PLAY_START_GONG",
  SET_SETTINGS = "SET_SETTINGS"
}
